version: '3'
services:
  backend:
    container_name: backend-app
    restart: always
    build: .
    ports:
      - "7500:7500"
    links:
      - mongo
  mongo:
    container_name: mongo-app
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'